#!/bin/sh
[ -f /etc/banner ] && cat /etc/banner

export PATH=/usr/bin:/usr/sbin:/bin:/sbin
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
export PS1='\u@\h:\w\$ '

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }
alias ...='cd ../..'
alias ..='cd ..'
alias cd..='cd ..'
alias cls='clear'
alias del='rm -i'
alias dir='ls -l -d'
alias e='exit'
alias la='ls -la'
alias ll='ls -l'
alias md='mkdir -p'
alias rd='rmdir'
alias psgrep='ps|grep'
